SB.Ball3DTournamentSys.Web/Areas/Member/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SB.Ball3DTournamentSys.Web.StringConsts;

namespace SB.Ball3DTournamentSys.Web.Areas.Member.Controllers
{
    [Authorize(Roles = ConstRoles.Member)]
    [Area(ConstAreas.Member)]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SB.Ball3DTournamentSys.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SB.Ball3DTournamentSys.Business.Interfaces;
using SB.Ball3DTournamentSys.DTO.DTOs.AppUserDto;
using SB.Ball3DTournamentSys.DTO.DTOs.GameServers;
using SB.Ball3DTournamentSys.DTO.DTOs.Tournament;
using SB.Ball3DTournamentSys.Entities.Concrete;
using SB.Ball3DTournamentSys.Web.BaseControllers;
using SB.Ball3DTournamentSys.Web.Models;
using SB.Ball3DTournamentSys.Web.StringConsts;

namespace SB.Ball3DTournamentSys.Web.Controllers
{
  
    public class HomeController : IdentityBaseController
    {
        private readonly IMapper _mapper;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;
        private readonly ITournamentService _tournamentService;
        public HomeController(ITournamentService tournamentService, IMapper mapper, SignInManager<AppUser> signInManager, UserManager<AppUser> userManager) : base(userManager)
        {
            _tournamentService = tournamentService;
            _mapper = mapper;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            //TODO: Refactor here, because now everytime it sends 3 unnecessary requests to database
            var upcomingTournaments = _mapper.Map<List<TournamentListAllDto>>(_tournamentService.GetUpcomingTournamentsWithAllTables());
            var finishedTournaments = _mapper.Map<List<TournamentListAllDto>>(_tournamentService.GetFinishedTournamentsWithAllTables());
            var startedTournaments = _mapper.Map<List<TournamentListAllDto>>(_tournamentService.GetStartedTournamentsWithAllTables());
            
            return View(new HomePageTournamentViewModel { FinishedTournaments = finishedTournaments, StartedTournaments=startedTournaments, UpcomingTournaments=upcomingTournaments});
        }

        public IActionResult Login()
        {
            if (IsLogged())
                return RedirectToAction("Index");
            return View(new AppUserLoginDTO());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(AppUserLoginDTO model)
        {
            if (ModelState.IsValid && !IsLogged())
            {
                var appUser = await _userManager.FindByNameAsync(model.UserName);
                if (appUser != null)
                {
                    var result = await _signInManager.PasswordSignInAsync(user:appUser, model.Password, model.RememberMe,false);
                    if (result.Succeeded)
                        return RedirectToAction("Index","Home");
                }
                ModelState.AddModelError("", "Username or pass are invalid.");
            }

            return View(model);
        }


        public IActionResult Register()
        {
            return View(new AppUserRegisterDTO());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(AppUserRegisterDTO model)
        {
            if(ModelState.IsValid)
            {
                var user = _mapper.Map<AppUser>(model);
                var registerResult = await _userManager.CreateAsync(user, model.Password);

                if (registerResult.Succeeded)
                {
                    await _userManager.AddToRoleAsync(user, "member");
                    return RedirectToAction("Login");
                }
                else
                {
                    foreach (var item in registerResult.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }
            }

            return View(model);
        }

        public IActionResult Logout()
        {
            if(User.Identity.IsAuthenticated)
                _signInManager.SignOutAsync();

            return RedirectToAction("Index");
        }


    }
}

SB.Ball3DTournamentSys.Web/Controllers/TournamentController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SB.Ball3DTournamentSys.Business.Concrete;
using SB.Ball3DTournamentSys.Business.Interfaces;
using SB.Ball3DTournamentSys.DTO.DTOs.PlayedGames;
using SB.Ball3DTournamentSys.DTO.DTOs.Tournament;
using SB.Ball3DTournamentSys.Entities.Concrete;
using SB.Ball3DTournamentSys.Web.BaseControllers;
using SB.Ball3DTournamentSys.Web.Models;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;

namespace SB.Ball3DTournamentSys.Web.Controllers
{
    public class TournamentController : IdentityBaseController
    {
        private readonly IMapper _mapper;
        private readonly ITournamentService _tournamentService;
        private readonly IPlayedGamesService _playedGamesService;
        private readonly ITournamentTeamsService _tournamentTeamsService;
        public TournamentController(IMapper mapper, ITournamentService tournamentService, IPlayedGamesService playedGamesService, ITournamentTeamsService tournamentTeamsService, UserManager<AppUser> userManager) : base(userManager) 
        {
            _mapper = mapper;
            _tournamentService = tournamentService;
            _playedGamesService = playedGamesService;
            _tournamentTeamsService = tournamentTeamsService;
        }
        public IActionResult Index(int? id)
        {
            if (!id.HasValue)
                return NotFound();

            var model = _mapper.Map<TournamentListAllDto>(_tournamentService.GetTournamentWithAllTablesById(id.Value));
            
            if (model == null)
                return NotFound();

            if(model.IsStarted && IsLogged())
            {
                ViewBag.Games = _mapper.Map<List<PlayedGamesListAllDto>>(_playedGamesService.GetTournamentGamesByUserIdWithAll(GetLoggedUser().Id, model.Id));
                ViewBag.LoggedUserId = GetLoggedUser().Id;
            }



            return View(model);
        }


        [Route("getBracket")]
        [HttpPost]
        public IActionResult GetTournamentBracket(int tournamentId)
        {
            var gameFixture = _playedGamesService.GetPlayedGamesWithAllTablesByTournamentId(tournamentId);
            BracketManager bm = new BracketManager(gameFixture);
            return Json(bm.GenerateBracketObject());
        }



    
    }
}

SB.Ball3DTournamentSys.Web/Views/Home/Index.cshtml
@model HomePageTournamentViewModel
@{
    ViewData["Title"] = "Home Page";
}


@section slider{
    <header>
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                @*<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>*@
            </ol>


            <div class="carousel-inner" role="listbox">
                <!-- Slide One - Set the background image for this slide in the line below -->
                <div class="carousel-item active" style="background-image: url('@Url.Content("~/img/b3d_index_main.jpg")');">
                    <div class="carousel-caption d-none d-md-block mb-4">
                        <h1>Welcome to Ball 3D Tournament System</h1>
                        <h2>Register your team and enjoy!</h2>
                    </div>
                </div>
            </div>

            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </header>
}

<!-- Marketing Icons Section -->
<div class="row mt-4">

    <div class="col-lg-4 mb-4">
        <div class="card h-100 shadow">
            <h4 class="card-header"><i class="fas fa-bolt mr-2"></i>Started Tournaments<i class="ml-2 fas fa-arrow-down"></i></h4>
            <div class="card-body">
                @if (Model.StartedTournaments.Count <= 0)
                {
                    <h6 class="text-info">There is no started tournaments yet.</h6>
                }
                else
                {
                    @foreach (var item in Model.StartedTournaments)
                    {
                        <live-tournaments Id="@item.Id" stadium-name="@item.Stadium.Name" tournament-type="@item.GameType" date="@item.StartDate.ToString("dd/MM/yyyy HH:mm CET")" team-count="@item.TournamentTeams.Count"></live-tournaments>
                    }

                }


            </div>
        </div>
    </div>

    <div class="col-lg-4 mb-4">
        <div class="card h-100 shadow">
            <h4 class="card-header"><i class="fas fa-hourglass-start mr-2"></i>Upcoming Tournaments<i class="ml-2 fas fa-arrow-down"></i></h4>
            <div class="card-body">
                @if (Model.UpcomingTournaments.Count <= 0)
                {
                    <h6 class="text-info">There is no upcoming tournaments yet.</h6>
                }
                else
                {
                    @foreach (var item in Model.UpcomingTournaments)
                    {
                        <upcoming-tournaments Id="@item.Id"  stadium-name="@item.Stadium.Name" tournament-type="@item.GameType" date="@item.StartDate.ToString("dd/MM/yyyy HH:mm CET")" team-count="@item.TournamentTeams.Count"></upcoming-tournaments>
                    }
                }

            </div>
        </div>
    </div>

    <div class="col-lg-4 mb-4">
        <div class="card h-100 shadow">
            <h4 class="card-header"><i class="fas fa-hourglass-end mr-2"></i>Finished Tournaments<i class="ml-2 fas fa-arrow-down"></i></h4>
            <div class="card-body">
                @if (Model.FinishedTournaments.Count <= 0)
                {
                    <h6 class="text-info">There is no finished tournaments yet.</h6>
                }
                else
                {
                    @foreach (var item in Model.FinishedTournaments)
                    {
                        var winnerTeam = item.TournamentTeams.Where(I => I.IsWinner).FirstOrDefault();
                        var winnerTag = string.Empty;
                        if (winnerTeam != null)
                        {
                            winnerTag = winnerTeam.Team?.Tag ?? string.Empty;
                        }
                      @*  <a asp-action="Index" asp-controller="Tournament" asp-route-id="{Id}"></a>*@
                        <finished-tournaments Id="@item.Id" stadium-name="@item.Stadium.Name" tournament-type="@item.GameType" date="@item.StartDate.ToString("dd/MM/yyyy HH:mm CET")" team-count="@item.TournamentTeams.Count" winner-team-tag="@winnerTag"></finished-tournaments>
                    }
                }

            </div>
        </div>
    </div>

</div>
<hr />
<div class="row">
    <div class="col-lg-6">
        <h2>What is Ball 3D Tournament System?</h2>
        <p>Ball 3D tournament system is created by Ball 3D admins. You can:</p>
        <ul>
            <li>
                <strong>Register your team into tournaments.</strong>
            </li>
            <li>3v3 Tournaments with awards</li>
            <li>5v5 Tournaments with awards</li>
            <li>National tournaments</li>
            <li>Championships</li>
        </ul>
    </div>
    <div class="col-lg-6">
        <img class="img-fluid rounded" src="~/img/b3d_sprint_cup.png" alt="">
    </div>
</div>
<!-- /.row -->

<hr>

SB.Ball3DTournamentSys.Web/Views/Home/Login.cshtml
@model AppUserLoginDTO
@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center my-4">Login</h1>
<form class="w-75 mx-auto my-2 p-4 shadow" method="post" asp-action="Login">
    <div class="form-group">
        <label asp-for="UserName">Username:</label>
        <span asp-validation-for="UserName" class="text-danger"></span>
        <input asp-for="UserName" class="form-control" value="" />
    </div>

    <div class="form-group">
        <label asp-for="Password">Password:</label>
        <span asp-validation-for="Password" class="text-danger"></span>
        <input type="password" asp-for="Password" class="form-control" />
    </div>

    <div class="form-check">
        <input asp-for="RememberMe" class="form-check-input" value="true" checked />
        <label class="form-check-label" asp-for="RememberMe">Remember me?</label>
        <span asp-validation-for="RememberMe" class="text-danger"></span>
    </div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <p>Dont you have account? <a asp-action="Register" class="btn-link">Register.</a></p>
    <button type="submit" class="btn btn-success">Login</button>

</form>

@section JavaScript{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

SB.Ball3DTournamentSys.Web/Views/Home/Register.cshtml
@model AppUserRegisterDTO
@{
    ViewData["Title"] = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="my-4 text-center"><i class="fas fa-user-plus mr-2"></i>Register</h1>

<form class="w-75 mx-auto my-2 p-4 shadow" method="post" asp-action="Register">
    <div class="form-group">
        <label asp-for="UserName">Username:</label>
        <span asp-validation-for="UserName" class="text-danger"></span>
        <input asp-for="UserName" class="form-control" value="" />
    </div>

    <div class="form-group">
        <label asp-for="Email">E Mail:</label>
        <span asp-validation-for="Email" class="text-danger"></span>
        <input asp-for="Email" class="form-control" value="" />
    </div>

    <div class="form-group">
        <label asp-for="Login">Ball 3D Nick:</label>
        <span asp-validation-for="Login" class="text-danger"></span>
        <input asp-for="Login" class="form-control" value="" />
    </div>

    <div class="form-group">
        <label asp-for="Password">Password:</label>
        <span asp-validation-for="Password" class="text-danger"></span>
        <input type="password" asp-for="Password" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="ConfirmPassword">Confirm Password:</label>
        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
        <input type="password" asp-for="ConfirmPassword" class="form-control" />
    </div>

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <p>Do you have account? <a asp-action="Login" class="btn-link">Login.</a></p>
    <button type="submit" class="btn btn-success">Register</button>

</form>

@section JavaScript{
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}