SB.Ball3DTournamentSys.Web/Areas/Admin/Controllers/PlayedGamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SB.Ball3DTournamentSys.Business.Concrete;
using SB.Ball3DTournamentSys.Business.Interfaces;
using SB.Ball3DTournamentSys.DTO.DTOs.PlayedGames;
using SB.Ball3DTournamentSys.Web.StringConsts;

namespace SB.Ball3DTournamentSys.Web.Areas.Admin.Controllers
{
    [Area(ConstAreas.Admin)]
    [Authorize(Roles = ConstRoles.Admin)]
    public class PlayedGamesController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IPlayedGamesService _playedGamesService;
        public PlayedGamesController(IPlayedGamesService playedGamesService, IMapper mapper)
        {
            _mapper = mapper;
            _playedGamesService = playedGamesService;
        }
        public IActionResult Index(int tournamentId)
        {
            return View(_mapper.Map<List<PlayedGamesListAllDto>>(_playedGamesService.GetPlayedGamesWithAllTablesByTournamentId(tournamentId)));
        }

        [HttpGet]
        public IActionResult UpdateScore(int matchId)
        {
            var model = _mapper.Map<UpdatePlayedGameDto>(_playedGamesService.GetAllById(matchId));
            if (model == null)
                return NotFound();
            return View(model);
        }


        [HttpPost]
        public IActionResult UpdateScore(UpdatePlayedGameDto model)
        {
            if (ModelState.IsValid)
            {
                var playedGame = _playedGamesService.GetById(model.Id);
                var winnerTeam = _playedGamesService.UpdateScore(playedGame, model.HomeTeamScore.Value, model.AwayTeamScore.Value);
                _playedGamesService.AddWinnerToNextGame(playedGame, winnerTeam);
            }
            else
            {
                model = _mapper.Map<UpdatePlayedGameDto>(_playedGamesService.GetAllById(model.Id));
                return View(model);
            }
            return RedirectToAction("Index", new { tournamentId = model.PlayedGamesRound.TournamentId });
        }
    }
}

SB.Ball3DTournamentSys.Web/Areas/Admin/Controllers/TournamentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SB.Ball3DTournamentSys.Business.Interfaces;
using SB.Ball3DTournamentSys.DTO.DTOs.Tournament;
using SB.Ball3DTournamentSys.Entities.Concrete;
using SB.Ball3DTournamentSys.Web.StaticVariables;
using SB.Ball3DTournamentSys.Web.StringConsts;

namespace SB.Ball3DTournamentSys.Web.Areas.Admin.Controllers
{
    [Area(ConstAreas.Admin)]
    [Authorize(Roles = ConstRoles.Admin)]
    public class TournamentController : Controller
    {
        private readonly IStadiumService _stadiumService;
        private readonly IGameServerService _gameServerService;
        private readonly ITournamentService _tournamentService;
        private readonly IMapper _mapper;
        private readonly ITeamService _teamService;
        private readonly ITournamentTeamsService _tournamentTeamsService;

        public TournamentController(IStadiumService stadiumService, IGameServerService gameServerService, ITournamentService tournamentService, IMapper mapper, ITeamService teamService, ITournamentTeamsService tournamentTeamsService)
        {
            _stadiumService = stadiumService;
            _gameServerService = gameServerService;
            _tournamentService = tournamentService;
            _teamService = teamService;
            _mapper = mapper;
            _tournamentTeamsService = tournamentTeamsService;
        }
        public IActionResult Index()
        {

            return View(_mapper.Map<List<TournamentListAllDto>>(_tournamentService.GetAllWithAllTables()));
        }

        public IActionResult CreateTournament()
        {
            ViewBag.Stadiums = new SelectList(_stadiumService.GetAll(), "Id", "Name");
            ViewBag.GameServers = new SelectList(_gameServerService.GetAll(), "Id", "ServerName");
            ViewBag.CetTime = StaticVars.CET_TIME;
            return View(new CreateTournamentDto());
        }

        public IActionResult Start(int id)
        {
            return View(_mapper.Map<StartTournamentDto>(_tournamentService.GetTournamentWithAllTablesById(id)));
        }

        [HttpPost]
        public IActionResult Start(StartTournamentDto model)
        {
            if (ModelState.IsValid)
            {
                _tournamentService.StartById(model.Id,_tournamentTeamsService.GetTournamentConfirmedTeamsByTournamentId(model.Id));
                return RedirectToAction("Index", "Tournament", new { area = String.Empty, id = model.Id });
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult CreateTournament(CreateTournamentDto model)
        {
            if (ModelState.IsValid)
            {
                var tournamentEntity = _mapper.Map<TournamentEntity>(model);
                _tournamentService.Add(tournamentEntity);
                return RedirectToAction("Index", "Home", new { area = String.Empty });
            }
            return View();
        }


/*        public IActionResult UpdateScore(int matchId)
        {
            var playedGame = _playedGamesService.GetById(matchId);
            var winnerTeam = _playedGamesService.UpdateScore(playedGame, 2, 3);
            FixtureManager fm = new FixtureManager(_playedGamesService);
            var nextTable = fm.FindTheNextTableForGame(playedGame);
            if (nextTable.HomeTeamId == null)
                nextTable.HomeTeamId = winnerTeam.Id;
            else
                nextTable.AwayTeamId = winnerTeam.Id;
            _playedGamesService.Update(nextTable);
            return RedirectToAction("Index");
        }*/
    }
}

SB.Ball3DTournamentSys.Web/Areas/Member/Controllers/ProtestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SB.Ball3DTournamentSys.Business.Interfaces;
using SB.Ball3DTournamentSys.DTO.DTOs.Protest;
using SB.Ball3DTournamentSys.DTO.DTOs.ProtestResponse;
using SB.Ball3DTournamentSys.Entities.Concrete;
using SB.Ball3DTournamentSys.Web.Areas.Member.Models;
using SB.Ball3DTournamentSys.Web.BaseControllers;
using SB.Ball3DTournamentSys.Web.StringConsts;

namespace SB.Ball3DTournamentSys.Web.Areas.Member.Controllers
{
    [Authorize(Roles = ConstRoles.Member)]
    [Area(ConstAreas.Member)]
    public class ProtestController : IdentityBaseController
    {
        private readonly IPlayedGamesService _playedGamesService;
        private readonly IMapper _mapper;
        private readonly IProtestService _protestService;
        private readonly IProtestResponseService _protestResponseService;
        public ProtestController(IPlayedGamesService playedGamesService, UserManager<AppUser> userManager, IMapper mapper, IProtestService protestService, IProtestResponseService protestResponseService) : base(userManager)
        {
            _playedGamesService = playedGamesService;
            _mapper = mapper;
            _protestService = protestService;
            _protestResponseService = protestResponseService;
        }

        public IActionResult Index()
        {
            return View(_mapper.Map<List<ProtestListAllDto>>(_protestService.GetAllByUserIdWithAll(GetLoggedUser().Id)));
        }

        public IActionResult ProtestDetails(int protestId)
        {
            var protest = _protestService.GetByIdWithAll(protestId);
            if (protest == null)
                return NotFound();

            if (!IsAuthorized(protest.AppUserId) && !IsAdmin())
                return Unauthorized();

            ViewBag.LoggedUserId = GetLoggedUser().Id;

            return View(new ProtestResponseListViewModel
            {
                Protest = _mapper.Map<ProtestListAllDto>(protest),
                ProtestResponses = _mapper.Map<List<ProtestResponseListAllDto>>(_protestResponseService.GetProtestResponsesByProtestIdWithAll(protestId))
            });
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddAnswer(CreateProtestResponseDto model)
        {
            if (!IsAuthorized(model.AppUserId) && !IsAdmin())
                return Unauthorized();
            if (ModelState.IsValid)
            {
                ProtestResponseEntity protestResponseEntity = new ProtestResponseEntity
                {
                    AppUserId = model.AppUserId,
                    Text = model.Text,
                    ProtestId = model.ProtestId
                };

                _protestResponseService.Add(protestResponseEntity);
            }

            return RedirectToAction("ProtestDetails", new { protestId = model.ProtestId });
        }
        public IActionResult AddProtest(int matchId)
        {
            var game = _playedGamesService.GetByIdWithTeamTable(matchId);
            if (game == null || game.HomeTeam == null || game.AwayTeam == null)
                return NotFound();

            ViewBag.LoggedUserId = GetLoggedUser().Id;
            ViewBag.Game = game;

            return View(new CreateProtestDto());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddProtest(CreateProtestDto model)
        {
            if (!IsAuthorized(model.AppUserId))
                return Unauthorized();

            if (ModelState.IsValid)
            {
                var entity = _mapper.Map<ProtestEntity>(model);
                _protestService.Add(entity);
                return RedirectToAction("Index", new { matchId = model.PlayedGameId });

            }
            var game = _playedGamesService.GetByIdWithTeamTable(model.PlayedGameId);
            ViewBag.LoggedUserId = GetLoggedUser().Id;
            ViewBag.Game = game;
            return View(model);
        }
    }
}

SB.Ball3DTournamentSys.Web/Areas/Member/Controllers/TournamentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SB.Ball3DTournamentSys.Business.Interfaces;
using SB.Ball3DTournamentSys.DTO.DTOs.Team;
using SB.Ball3DTournamentSys.DTO.DTOs.Tournament;
using SB.Ball3DTournamentSys.Entities.Concrete;
using SB.Ball3DTournamentSys.Web.StringConsts;

namespace SB.Ball3DTournamentSys.Web.Areas.Member.Controllers
{
    [Area(ConstAreas.Member)]
    [Authorize(Roles = ConstRoles.Member)]
    public class TournamentController : Controller
    {

        private readonly IMapper _mapper;
        private readonly ITeamService _teamService;
        private readonly UserManager<AppUser> _userManager;
        private readonly ITournamentService _tournamentService;
        private readonly ITournamentTeamsService _tournamentTeamsService;
        public TournamentController(IMapper mapper, ITeamService teamService, UserManager<AppUser> userManager, ITournamentService tournamentService, ITournamentTeamsService tournamentTeamsService)
        {
            _mapper = mapper;
            _teamService = teamService;
            _userManager = userManager;
            _tournamentService = tournamentService;
            _tournamentTeamsService = tournamentTeamsService;

        }
        public IActionResult Register(int id)
        {
            var loggedUserId = _userManager.FindByNameAsync(User.Identity.Name).Result.Id;
            RegisterTeamDto model = new RegisterTeamDto
            {
                OwnedTeams = _mapper.Map<List<TeamListDto>>(_teamService.GetOwnedTeamsByUserId(loggedUserId)),
                Tournament = _mapper.Map<TournamentListAllDto>(_tournamentService.GetTournamentWithAllTablesById(id)),
                AppUserId = loggedUserId
            };

            return View(model);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(RegisterTeamDto model)
        {
            var loggedUserId = _userManager.FindByNameAsync(User.Identity.Name).Result.Id;
            var tournament = _tournamentService.GetById(model.TournamentId);

            if (loggedUserId != model.AppUserId)
                return Unauthorized();

            if (ModelState.IsValid)
            {
                _tournamentTeamsService.Add(new TournamentTeamsEntity
                {
                    TeamId = model.TeamId,
                    TournamentId = model.TournamentId,
                    IsConfirmed = tournament.StartDate.AddMinutes(-30) <= DateTime.Now ? true : false
                });

                return RedirectToAction("Index", "Tournament", new { area = "", id = model.TournamentId });
            }

            model.OwnedTeams = _mapper.Map<List<TeamListDto>>(_teamService.GetOwnedTeamsByUserId(_userManager.FindByNameAsync(User.Identity.Name).Result.Id));

            model.Tournament = _mapper.Map<TournamentListAllDto>(_tournamentService.GetTournamentWithAllTablesById(model.TournamentId));

            return View(model);
        }

        public IActionResult Confirm(int id)
        {
           // TODO: Refactor here


            var loggedUserId = _userManager.FindByNameAsync(User.Identity.Name).Result.Id;
            var tournament = _tournamentService.GetTournamentWithAllTablesById(id);

            if (tournament == null)
                return NotFound();

            if(tournament.IsStarted)
            {
                throw new Exception("Tournament is already started :(");
            }

            foreach (var item in tournament.TournamentTeams)
            {
                if (item.Team.AppUserId == loggedUserId) // it means user is registered his team to this tournament, so confirm it
                {
                    if (!item.IsConfirmed)
                    {
                        _tournamentTeamsService.ConfirmRegisterStatus(item.Team, tournament.Id);
                    }
                    return RedirectToAction("Index", "Tournament", new { area = "", id = id });
                }
            }

            return RedirectToAction("Register", "Tournament", new { area = ConstAreas.Member, id = id });

        }


    }
}

SB.Ball3DTournamentSys.Web/Controllers/TournamentController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SB.Ball3DTournamentSys.Business.Concrete;
using SB.Ball3DTournamentSys.Business.Interfaces;
using SB.Ball3DTournamentSys.DTO.DTOs.PlayedGames;
using SB.Ball3DTournamentSys.DTO.DTOs.Tournament;
using SB.Ball3DTournamentSys.Entities.Concrete;
using SB.Ball3DTournamentSys.Web.BaseControllers;
using SB.Ball3DTournamentSys.Web.Models;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;

namespace SB.Ball3DTournamentSys.Web.Controllers
{
    public class TournamentController : IdentityBaseController
    {
        private readonly IMapper _mapper;
        private readonly ITournamentService _tournamentService;
        private readonly IPlayedGamesService _playedGamesService;
        private readonly ITournamentTeamsService _tournamentTeamsService;
        public TournamentController(IMapper mapper, ITournamentService tournamentService, IPlayedGamesService playedGamesService, ITournamentTeamsService tournamentTeamsService, UserManager<AppUser> userManager) : base(userManager) 
        {
            _mapper = mapper;
            _tournamentService = tournamentService;
            _playedGamesService = playedGamesService;
            _tournamentTeamsService = tournamentTeamsService;
        }
        public IActionResult Index(int? id)
        {
            if (!id.HasValue)
                return NotFound();

            var model = _mapper.Map<TournamentListAllDto>(_tournamentService.GetTournamentWithAllTablesById(id.Value));
            
            if (model == null)
                return NotFound();

            if(model.IsStarted && IsLogged())
            {
                ViewBag.Games = _mapper.Map<List<PlayedGamesListAllDto>>(_playedGamesService.GetTournamentGamesByUserIdWithAll(GetLoggedUser().Id, model.Id));
                ViewBag.LoggedUserId = GetLoggedUser().Id;
            }



            return View(model);
        }


        [Route("getBracket")]
        [HttpPost]
        public IActionResult GetTournamentBracket(int tournamentId)
        {
            var gameFixture = _playedGamesService.GetPlayedGamesWithAllTablesByTournamentId(tournamentId);
            BracketManager bm = new BracketManager(gameFixture);
            return Json(bm.GenerateBracketObject());
        }



    
    }
}

SB.Ball3DTournamentSys.Web/Views/Tournament/Index.cshtml
@model TournamentListAllDto
@{
    ViewData["Title"] = ($"{Model.Name} {Model.GameType}v{Model.GameType}");
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<PlayedGamesListAllDto> teamOwnerGameList = null;
    int? loggedUserId = null;
    if (ViewBag.LoggedUserId != null)
    {
        loggedUserId = ViewBag.LoggedUserId;
    }
    if (ViewBag.Games != null)
    {
        teamOwnerGameList = ViewBag.Games;
    }
}
<link href="~/css/jquery.bracket.min.css" rel="stylesheet" />
<h2 class="mt-4">@Model.Name <span class="card-text badge badge-success p-2 badge-pill"><strong>@Model.GameType v @Model.GameType - @Model.Stadium.Name</strong></span></h2>
<hr />

<ul class="nav nav-tabs my-4 border-light">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#home"><i class="fas fa-home mr-2"></i>Home</a>
    </li>


    <li class="nav-item">
        <a class="@(Model.IsStarted ? "nav-link" : "nav-link disabled")" data-toggle="tab" href="#bracket"><i class="fas fa-trophy mr-2"></i>Bracket</a>
    </li>

    <li class="nav-item">
        <a class="@(Model.IsStarted ? "nav-link" : "nav-link disabled")" data-toggle="tab" href="#matches"><i class="fas fa-futbol mr-2"></i>My Matches</a>
    </li>

</ul>

<div id="myTabContent" class="tab-content">
    <div class="tab-pane fade show active" id="home">
        <div class="row">

            <div class="col-md-6">
                <div class="card border-dark mb-3">
                    <div class="card-header"><i class="fas fa-quote-left mr-2"></i>Description</div>
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                    </div>
                </div>

                @if (User.IsInRole("admin"))
                {
                    <div class="card  border-dark mb-3">
                        <div class="card-header bg-warning text-white"><i class="fas fa-user-shield mr-2"></i>Admin Actions</div>
                        <div class="card-body">
                            @if (!Model.IsStarted)
                            {
                                <a asp-action="Start" asp-controller="Tournament" asp-area="Admin" asp-route-id="@Model.Id" class="btn btn-success btn-block"><i class="fas fa-play-circle mr-2"></i>Start Tournament</a>
                            }
                            else if (!Model.IsFinished)
                            {
                                <a asp-action="Start" asp-controller="Tournament" asp-area="Admin" asp-route-id="@Model.Id" class="btn btn-danger btn-block"><i class="fas fa-stop-circle mr-2"></i>Finish Tournament</a>
                                <a asp-action="Index" asp-controller="PlayedGames" asp-area="Admin" asp-route-tournamentId="@Model.Id" class="btn btn-info btn-block"><i class="fas fa-tasks mr-2"></i>Manage Games</a>
                            }
                        </div>
                    </div>
                }
            </div>



            <div class="col-md-6">
                <div class="card border-dark mb-3" style="max-height:400px;overflow:auto">
                    <div class="card-header"><i class="fas fa-list mr-2"></i>Registered Teams</div>
                    <div class="card-body">
                        @if (Model.IsStarted)
                        {
                            <div class="alert-info mb-2 text-light p-2"><i class="fas fa-info-circle mr-2"></i><strong>Tournament is started!</strong></div>
                        }
                        @foreach (var item in Model.TournamentTeams)
                        {
                            if (item.IsConfirmed)
                            {
                                <div><i class="fas fa-check-square" style="color:green"></i><strong>  @item.Team.Name - (@item.Team.Tag) </strong>(CONFIRMED) </div>
                            }
                            else
                            {
                                <div><i class="fas fa-check-square" style="color:gold"></i><strong> @item.Team.Name - (@item.Team.Tag) </strong>(Waiting for confirm...) </div>
                            }
                        }
                        @if (!Model.IsStarted)
                        {
                            <div class="alert-info mt-2 text-light p-1"><i class="fas fa-info-circle mr-2"></i>Confirmations will start at <strong>@Model.StartDate.AddMinutes(-30).ToString("dd/MM/yyyy HH:mm CET")</strong></div>
                        }
                    </div>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    if (!Model.IsStarted)
                    {
                        if (Model.StartDate.AddMinutes(-30) <= DateTime.Now)
                        {
                            <a asp-action="Confirm" asp-controller="Tournament" asp-area="Member" asp-route-id="@Model.Id" class="btn btn-info btn-block"><i class="fas fa-check-circle mr-2"></i>Confirm Registration & Fast Register</a>
                        }
                        else
                        {
                            <a asp-action="Register" asp-controller="Tournament" asp-area="Member" asp-route-id="@Model.Id" class="btn btn-success btn-block"><i class="fas fa-check-circle mr-2"></i>Register your team!</a>

                        }
                    }
                    else
                    {
                        <a href="#bracket" class="btn btn-info btn-block"><i class="fas fa-info-circle mr-2"></i>Tournament is started.</a>
                    }


                }
                else
                {
                    <a asp-action="Login" asp-controller="Home" asp-area="" class="btn btn-info btn-block">You need to login for register your team to this tournament!</a>
                }
                <a asp-action="Index" asp-controller="Home" asp-area="" class="btn btn-light btn-block mb-2"><i class="fas fa-arrow-left mr-2"></i>Back</a>

            </div>



        </div>



    </div>


    <div class="tab-pane fade" id="matches">
        @if (Model.IsStarted && teamOwnerGameList != null && User.Identity.IsAuthenticated)
        {
            var currentRoundNumber = 0;
            <table class="table table-hover w-75 mx-auto shadow table-bordered">

                @foreach (var item in teamOwnerGameList)
                {
                    if (currentRoundNumber == 0)
                    {

                        <tr class="text-center">
                            <th>Home Team</th>
                            <th>Score</th>
                            <th>Away Team</th>
                            <th>-/+</th>
                        </tr>
                    }

                    if (item.RoundNumber != currentRoundNumber)
                    {
                        currentRoundNumber = item.RoundNumber;
                        <tr class="text-center">
                            <td colspan="4" class="bg-secondary text-white"><strong><i class="fas fa-futbol mr-2"></i>ROUND @currentRoundNumber<i class="fas fa-arrow-alt-circle-down ml-2"></i></strong></td>

                        </tr>
                    }
                    <tr class="text-center">


                        @if (item.IsFinished)
                        {
                            <td>@(item.HomeTeam?.Tag ?? "BYE")</td>
                            <td><span style="font-size:large">@(item.HomeTeamScore == null ? "" : item.HomeTeamScore.ToString())<strong> - </strong>@(item.AwayTeamScore == null ? "" : item.AwayTeamScore.ToString()) </span></td>
                            <td>@(item.AwayTeam?.Tag ?? "BYE")</td>
                            <td><p class="badge badge-success p-2" style="font-size:small"><i class="fas fa-check mr-2"></i>CONFIRMED / FINISHED</p></td>
                        }
                        else
                        {
                            <td>@(item.HomeTeam?.Tag ?? "Waiting..")</td>
                            <td><span style="font-size:large">@(item.HomeTeamScore == null ? "" : item.HomeTeamScore.ToString())<strong> - </strong>@(item.AwayTeamScore == null ? "" : item.AwayTeamScore.ToString()) </span></td>
                            <td>@(item.AwayTeam?.Tag ?? "Waiting..")</td>
                            if (item.HomeTeam != null && item.AwayTeam != null)
                            {
                                if ((item.IsHomeTeamConfirmedResult && item.HomeTeam.AppUserId == loggedUserId) || (item.IsAwayTeamConfirmedResult && item.AwayTeam.AppUserId == loggedUserId))
                                {
                                    <td>
                                        <p class="badge badge-warning p-2" style="font-size:small"><i class="fas fa-check mr-2"></i>You confirmed the result. Waiting for other team owner.</p>
                                        <a asp-action="UpdateScore" asp-controller="PlayedGames" asp-area="Member" asp-route-matchId="@item.Id" class="btn btn-info btn-sm"><i class="fas fa-edit mr-2"></i>Edit Result</a>

                                        <span class="badge badge-primary p-2 mt-1" style="font-size:small"><i class="fas fa-info-circle mr-2"></i> If other team captain is not confirming the result, <a class="btn-link" asp-action="AddProtest" asp-controller="Protest" asp-area="Member" asp-route-matchId="@item.Id"><strong>click here for open protest!</strong></a></span>
                                    </td>

                                }
                                else
                                {
                                    @if (item.IsAwayTeamConfirmedResult || item.IsHomeTeamConfirmedResult)
                                    {
                                        <td>
                                            <div>
                                                <form asp-action="ConfirmResult" asp-controller="PlayedGames" asp-area="Member">
                                                    <input type="hidden" name="matchId" value="@item.Id" />
                                                    <button type="submit" onclick="return confirm('Are you sure you want to confirm this game?')" class="btn btn-info"><i class="fas fa-check-circle mr-2"></i>Confirm Result <strong>(@item.HomeTeam.Tag @item.HomeTeamScore - @item.AwayTeamScore @item.AwayTeam.Tag)</strong></button><br />
                                                </form>

                                                <span class="badge badge-primary p-2 mt-1" style="font-size:small"><i class="fas fa-info-circle mr-2"></i> If the result is not true, <a class="btn-link" asp-action="AddProtest" asp-controller="Protest" asp-area="Member" asp-route-matchId="@item.Id"><strong>click here for open protest!</strong></a></span>
                                            </div>
                                        </td>
                                    }
                                    else
                                    {
                                        <td>
                                            <a asp-action="UpdateScore" asp-controller="PlayedGames" asp-area="Member" asp-route-matchId="@item.Id" class="btn btn-info"><i class="fas fa-check mr-2"></i>Add Result</a>

                                        </td>
                                    }

                                }
                            }
                        }
                    </tr>
                }

            </table>
        }
    </div>

    <div class="tab-pane fade my-4 pl-5 w-75 mx-auto border border-light" id="bracket">
        <div class="bracket">
        </div>
    </div>

</div>


@section JavaScript{
    <script src="~/js/jquery.bracket.min.js"></script>
    <script>
        var bracketData;
        var isBracketActivated;

        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            var target = $(e.target).attr("href") // activated tab
            if (target == "#bracket" && !isBracketActivated) {

                $.ajax({
                       method: "POST",
                       url: "/getBracket",
                       contentType: "application/x-www-form-urlencoded; charset=UTF-8",
                       dataType: "json",
                       data: {tournamentId:@Model.Id},
                       success: function (data) {
                           bracketData = data;
                           $('.bracket').bracket({

                               init: bracketData /* data to initialize the bracket with */
                           })
                           isBracketActivated = true;
                       },
                       error: function (e) {
                           console.log(e);
                       }
                })

            }
        });

    </script>

}